version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data
    networks:
      - elastic_net
      
networks:
  elastic_net:
    driver: bridge