version: '3.9'
# influxdb、cadvisor、grafana监控
volumes:
  influxdb_data: {}
  grafana_data: {}

services:    
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    environment:
      - flux-enabled=true
      - INFLUXDB_DB=cadvisor
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=12345678
      - TZ=Asia/Shanghai
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    privileged: true
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086 -storage_driver_user=root -storage_driver_password=12345678
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influxdb
    links:
      - influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    links:
      - influxdb