version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.8.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=12345678
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge