version: "2"
services:
  nacos1:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos1
    restart: always
    networks:
      nacos_net:
        ipv4_address: 172.16.238.11
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    env_file:
      - ./env/nacos-ip.env
    depends_on:
      - nacos-nginx

  nacos2:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos2
    restart: always
    networks:
      nacos_net:
        ipv4_address: 172.16.238.12
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    env_file:
      - ./env/nacos-ip.env
    depends_on:
      - nacos-nginx
  nacos3:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos3
    restart: always
    networks:
      nacos_net:
        ipv4_address: 172.16.238.13
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    env_file:
      - ./env/nacos-ip.env
    depends_on:
      - nacos-nginx
  nacos-mysql: # nacos2.X版本需要手动更新一下sql
    container_name: nacos-mysql
    image: nacos/nacos-mysql:5.7
    restart: always
    networks:
      nacos_net:
        ipv4_address: 172.16.238.14
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  nacos-nginx:
    container_name: nacos-nginx
    image: nginx
    restart: always
    networks:
      nacos_net:
        ipv4_address: 172.16.238.15
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8848:80"

networks:
  nacos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
