version: '3.9'
services:
  mysql:
    image: mysql:5.7.38
    container_name: mysql
    restart: always 
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./data:/var/lib/mysql
    networks:
      - mysql

networks:
   mysql: