version: '3.9'
services:
  redis-node1-6371:
    image: 	redis:6.2.7-alpine
    container_name: redis-node1-6371
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6371:6379
    volumes:
      - ./conf/node1_6371:/usr/local/etc/redis
      - node1_6371_data:/data

  redis-node2-6372:
    image: redis:6.2.7-alpine
    container_name: redis-node2-6372
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6372:6379
    volumes:
      - ./conf/node1_6372:/usr/local/etc/redis
      - node2_6372_data:/data

  redis-node3-6373:
    image: redis:6.2.7-alpine
    container_name: redis-node3-6373
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6373:6379
    volumes:
      - ./conf/node1_6373:/usr/local/etc/redis
      - node3_6373_data:/data

  redis-node4-6374:
    image: redis:6.2.7-alpine
    container_name: redis-node4-6374
    restart: always
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6374:6379
    volumes:
      - ./conf/node1_6374:/usr/local/etc/redis
      - node4_6374_data:/data

  redis-node5-6375:
    image: redis:6.2.7-alpine
    container_name: redis-node5-6375
    restart: always
    environment:
      - TZ=Asia/Shanghai   
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6375:6379
    volumes:
      - ./conf/node1_6375:/usr/local/etc/redis
      - node5_6375_data:/data

  redis-node6-6376:
    image: redis:6.2.7-alpine
    container_name: redis-node6-6376
    restart: always
    environment:
      - TZ=Asia/Shanghai   
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6376:6379
    volumes:
      - ./conf/node1_6376:/usr/local/etc/redis
      - node6_6376_data:/data

volumes:
  node1_6371_data:
  node2_6372_data:
  node3_6373_data:
  node4_6374_data:
  node5_6375_data:
  node6_6376_data: