version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:${NACOS_VERSION}
    restart: always
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    env_file:
      - ./env/nacos-hostname.env
    depends_on:
      - nacos-mysql

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos2
    restart: always
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    env_file:
      - ./env/nacos-hostname.env
    depends_on:
      - nacos-mysql
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos3
    restart: always
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
    env_file:
      - ./env/nacos-hostname.env
    depends_on:
      - nacos-mysql
  nacos-mysql: # nacos2.X版本需要手动更新一下sql
    container_name: nacos-mysql
    image: nacos/nacos-mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  nacos-nginx:
    container_name: nacos-nginx
    image: nginx
    restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8848:80"
